### ISSUE TITLE
Cannot view new parkinglots

### ISSUE THREAD

**Issue by fazlul-01** [Joysond/ParkingSystem#1]
why is it returning only the first parking lot instead of returning all in the get request???

**Comment by Joysond** [comment]
> why is it returning only the first parking lot instead of returning all in the get request???

[Code Link](https://github.com/Joysond/ParkingSystem/blob/master/parkingsystem/src/main/java/com/accolite/parkingsystem/service/ParkingSystemServiceImpl.java#L54) check this link, here I am returning only the first entry, You could change it to return all the parking lots

**Comment by fazlul-01** [comment]
thanks for your reply **Joysond**, this is very helpful for my project.

I'm also facing another issue....it would be really helpful if you can fix this for me.
I used MySQL as database and I getting a wired issue with the primary key generation for section and parkinglot

![Annotation 2020-07-17 173442](https://user-images.githubusercontent.com/44228070/87784525-1ac2bf00-c854-11ea-9c68-18ff80c33277.png)

You can see that after the first two values the number pops to 52
and,
![Annotation 2020-07-17 173610](https://user-images.githubusercontent.com/44228070/87784658-578eb600-c854-11ea-813a-99acb19b3f61.png)
similar issue with the sections table, after the number 10 the value jumps to 52


pls....help me to resolve this

**Comment by Joysond** [comment]
@fazlul-01 Why do you need these id values in order? I guess this id generator keeps track of all the primary ids across the database table and that is why these ids are not in sequence for a single table
